[platformio]
default_envs = parent, child100
[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
board = rpipico2w
framework = arduino
monitor_speed = 115200
build_flags = -Icommon
extra_scripts = pre:scripts/embed_web.py
lib_deps =
    adafruit/Adafruit BusIO@1.17.4
    adafruit/Adafruit Unified Sensor@1.1.15
[env:parent]
build_flags = ${env.build_flags} -DBOARD_PARENT -DIMU_HZ=50
[env:child50]
build_flags = ${env.build_flags} -DIMU_HZ=50
[env:child100]
build_flags = ${env.build_flags} -DIMU_HZ=100
